### ISSUE TITLE
FileExistsError: [WinError 183] Cannot create a file when that file already exists:

### ISSUE THREAD

**Issue by Fit-yourself** [piglei/ai-vocabulary-builder#11]
謝謝你解決了 #9 問題，爲了測驗功能完整性，我嘗試手動編輯選擇單詞，但遇到了問題：

当 Enter `no` 之后
```
> Enter text: no
"humbly" was discarded, preparing other words...
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\Scripts\aivoc.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\voc_builder\main.py", line 39, in main
    enter_interactive_mode()
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\voc_builder\interactive.py", line 75, in enter_interactive_mode
    handle_cmd_no()
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\voc_builder\interactive.py", line 96, in handle_cmd_no
    get_csv_builder().remove_words({ret.word_sample.word})
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\voc_builder\builder.py", line 103, in remove_words
    os.rename(new_path, self.file_path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\xxx\\aivoc_builder.csv.new' -> 'C:\\Users\\xxx\\aivoc_builder.csv'
```

### 系統信息
- Windows 11 22621
- Python 3.10.8

**Comment by piglei** [comment]
不好意思，确认是 Windows 环境下的一个 bug。麻烦再更新一下版本，到 0.1.3 版本，应该就 OK 了。

**Comment by Fit-yourself** [comment]
謝謝，可以使用了！
